// frontend/examples/frameworks/react-form/src/App.js
import React, { useState } from 'react';
import './App.css';

function App() {
  const [nome, setNome] = useState('');
  const [email, setEmail] = useState('');
  const [senha, setSenha] = useState('');
  const [mensagem, setMensagem] = useState('');

  const validarEmail = (email) => {
    const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return re.test(email);
  };

  const handleSubmit = (event) => {
    event.preventDefault();

    if (nome && email && senha) {
      if (!validarEmail(email)) {
        setMensagem("Por favor, preencha um email válido.");
      } else {
        setMensagem("Cadastro realizado com sucesso!");
      }
    } else {
      setMensagem("Por favor, preencha todos os campos.");
    }
  };

  return (
    <div className="App">
      <h1>Cadastro de Usuário</h1>
      <form onSubmit={handleSubmit}>
        <label htmlFor="nome">Nome:</label>
        <input type="text" id="nome" value={nome} onChange={(e) => setNome(e.target.value)} required />

        <label htmlFor="email">Email:</label>
        <input type="email" id="email" value={email} onChange={(e) => setEmail(e.target.value)} required />

        <label htmlFor="senha">Senha:</label>
        <input type="password" id="senha" value={senha} onChange={(e) => setSenha(e.target.value)} required />

        <button type="submit">Cadastrar</button>
      </form>

      <div id="mensagem">{mensagem}</div>
    </div>
  );
}

export default App;

// frontend/examples/frameworks/angular-form/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true, // Define o componente como standalone
  imports: [FormsModule], // Importa o FormsModule para o uso do ngModel
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  nome: string = '';
  email: string = '';
  senha: string = '';
  mensagem: string = '';

  validarEmail(email: string): boolean {
    const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return re.test(email);
  }

  onSubmit() {
    if (this.nome && this.email && this.senha) {
      if (!this.validarEmail(this.email)) {
        this.mensagem = "Por favor, preencha um email válido.";
      } else {
        this.mensagem = "Cadastro realizado com sucesso!";
      }
    } else {
      this.mensagem = "Por favor, preencha todos os campos.";
    }
  }
}

<div class="container">
  <h1>Cadastro de Usuário</h1>
  
  <form (ngSubmit)="onSubmit()" #cadastroForm="ngForm">
    <label for="nome">Nome:</label>
    <input type="text" id="nome" [(ngModel)]="nome" name="nome" required />

    <label for="email">Email:</label>
    <input type="email" id="email" [(ngModel)]="email" name="email" required />

    <label for="senha">Senha:</label>
    <input type="password" id="senha" [(ngModel)]="senha" name="senha" required />

    <button type="submit">Cadastrar</button>
  </form>

  <div id="mensagem">{{ mensagem }}</div>
</div>
